"use client";
import {useQuery} from "@tanstack/react-query";
import {ArrowLeft,AlertTriangle,CheckCircle2,LoaderCircle} from "lucide-react";
import Link from "next/link";
import {useParams} from "next/navigation";
import {AppShell} from "../../../components/app-shell";
import {Badge,Card} from "../../../components/ui";
import {getIncident,ComplaintIndicator,Incident} from "../../../lib/api";
import {ErrorState,LoadingState} from "../../../components/async-state";

export default function IncidentDetail(){const {id}=useParams<{id:string}>();const query=useQuery({queryKey:["incident",id],queryFn:()=>getIncident(id),refetchInterval:data=>data.state.data?.status==="queued"||data.state.data?.status==="analysing"?2000:false});const data=query.data;if(query.isLoading)return <AppShell><LoadingState label="Loading incident…"/></AppShell>;if(query.isError||!data)return <AppShell><ErrorState message="Incident not found or unavailable." onRetry={()=>query.refetch()}/></AppShell>;const completed=data.status==="completed";const extraction=data.complaint_extraction;const triggered=data.suspicion_indicators?.filter(item=>item.triggered)||[];return <AppShell><Link href="/incidents" className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={14}/> Incidents</Link><div className="mx-auto max-w-3xl"><p className="mono text-xs text-muted-foreground">{id}</p><div className="mt-3 flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">{completed?"Incident analysis":"Incident intake secured"}</h1><p className="mt-2 text-sm text-muted-foreground">{completed?"Technical evidence and transparent interpretation rules are available for review.":"The suspicious copy and optional evidence are private and ready for analysis."}</p></div><Badge tone={data.status==="failed"?"review":completed?"secured":"processing"}>{data.status}</Badge></div>{completed?<><Comparison data={data}/><ScoreCard data={data} triggered={triggered}/><ComplaintCard extraction={extraction}/><CommunityCard data={data}/><EvidenceCard data={data}/></>:<Pending data={data}/>}<Card className="mt-5 p-5"><h2 className="font-semibold">Activity</h2><div className="mt-5 space-y-3">{data.events?.map(event=><div className="flex gap-4" key={`${event.timestamp}-${event.message}`}><span className="mono w-24 shrink-0 text-[11px] text-muted-foreground">{new Date(event.timestamp).toLocaleTimeString()}</span><span className="text-sm">{event.message}</span></div>)}</div></Card><div className="mt-8 flex items-center gap-2 text-xs text-muted-foreground"><AlertTriangle size={14}/> Technical evidence only. CreatorShield does not determine ownership or unlawful conduct.</div></div></AppShell>}
function Comparison({data}:{data:Incident}){return <Card className="mt-8 p-6"><div className="flex items-center gap-3"><CheckCircle2 className="text-green-600" size={20}/><div><h2 className="font-semibold">Comparison results</h2><p className="mt-1 text-sm text-muted-foreground">Transcript comparison is unavailable in this local milestone and is shown explicitly below.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Score label="Combined similarity" value={data.combined_similarity}/><Score label="Visual similarity" value={data.visual_similarity}/><Score label="Audio similarity" value={data.audio_similarity}/><Score label="Timeline confidence" value={data.timeline_confidence}/></div><Link href={`/reports/${data.incident_id}`} className="mt-5 inline-flex items-center text-sm font-medium text-blue-600 hover:underline">Open evidence report preview</Link></Card>}
function ScoreCard({data,triggered}:{data:Incident;triggered:ComplaintIndicator[]}){return <Card className="mt-5 p-6"><h2 className="font-semibold">Transparent suspicion score</h2><div className="mt-4 flex flex-wrap items-end gap-4"><div className="text-4xl font-semibold">{data.suspicion_score??"Unavailable"}<span className="ml-1 text-base font-normal text-muted-foreground">/100</span></div>{data.suspicion_band&&<Badge tone="review">{data.suspicion_band}</Badge>}</div><p className="mt-3 text-sm text-muted-foreground">This is an evidence review aid, not a finding of fraud, ownership, or unlawful conduct.</p>{triggered.length?<div className="mt-6 space-y-3">{triggered.map(item=><Indicator key={item.rule} item={item}/>)}</div>:<p className="mt-6 text-sm text-muted-foreground">No configured suspicion indicators were triggered.</p>}</Card>}
function ComplaintCard({extraction}:{extraction:Incident["complaint_extraction"]}){return <Card className="mt-5 p-6"><h2 className="font-semibold">Complaint evidence</h2><p className="mt-1 text-sm text-muted-foreground">Extraction and interpretation are shown separately.</p><div className="mt-5 rounded-lg bg-muted p-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Extraction status</span><span className="font-medium">{extraction?.status||"Unavailable"}</span></div><div className="mt-2 flex justify-between"><span className="text-muted-foreground">Provider</span><span className="font-medium">{extraction?.provider||"Local fallback"}</span></div></div><div className="mt-5 space-y-2">{extraction?.files?.map(file=><div key={file.filename} className="flex justify-between gap-4 border-b pb-2 text-sm"><span>{file.filename}</span><span className="text-right text-muted-foreground">{file.status}</span></div>)}</div>{extraction?.fields&&Object.keys(extraction.fields).length>0?<div className="mt-6 border-t pt-5"><h3 className="text-sm font-medium">Extracted fields</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(extraction.fields).map(([key,value])=><div key={key}><div className="text-xs capitalize text-muted-foreground">{key.replaceAll("_"," ")}</div><div className="mt-1 break-words text-sm">{Array.isArray(value)?value.join(", "):String(value)}</div></div>)}</div></div>:null}</Card>}
function CommunityCard({data}:{data:Incident}){const summary=data.community_summary;return <Card className="mt-5 border-dashed p-6"><h2 className="font-semibold">Simulated community intelligence</h2><p className="mt-1 text-sm text-muted-foreground">Seeded development data only; these are not verified real-world findings.</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Signal label="Related simulated reports" value={String(summary?.related_report_count??0)}/><Signal label="Payment-demand occurrences" value={String(summary?.payment_demand_occurrences??0)}/><Signal label="Creator restrictions" value={String(summary?.creator_restrictions??0)}/><Signal label="First recorded date" value={summary?.first_recorded_date||"Unavailable"}/></div>{data.community_matches?.length?<div className="mt-6 space-y-2 border-t pt-5">{data.community_matches.map(match=><div className="flex flex-wrap justify-between gap-2 rounded-lg border p-3 text-sm" key={`${match.report_id}-${match.identifier}`}><span>{match.identifier}</span><span className="text-muted-foreground">Matched: {match.matched_value}</span></div>)}</div>:<p className="mt-5 text-sm text-muted-foreground">No matching simulated identifiers were found.</p>}</Card>}
function EvidenceCard({data}:{data:Incident}){return <Card className="mt-5 p-6"><h2 className="font-semibold">Evidence signals</h2><div className="mt-5 grid gap-4 sm:grid-cols-3"><Signal label="Matching segments" value={String(data.matching_segments??0)}/><Signal label="Matching audio" value={`${(data.matching_audio_seconds??0).toFixed(1)} seconds`}/><Signal label="Transcript similarity" value="Unavailable"/></div>{data.modifications?.length?<div className="mt-6 border-t pt-5"><h3 className="text-sm font-medium">Modification indicators</h3><ul className="mt-3 space-y-2">{data.modifications.map(item=><li className="text-sm text-muted-foreground" key={item}>• {item}</li>)}</ul></div>:null}</Card>}
function Pending({data}:{data:Incident}){return <Card className="mt-8 p-6"><div className="flex items-center gap-3"><LoaderCircle className="animate-spin text-blue-600" size={18}/><div><p className="text-sm font-medium">{data.status==="failed"?"Analysis failed":"Queued for analysis"}</p><p className="mt-1 text-xs text-muted-foreground">{data.status==="failed"?"The processing event stream contains the failure reason.":"Comparison and complaint analysis run in the worker. No score is shown before analysis completes."}</p></div></div><div className="mt-8 space-y-4"><Step done label="Original proof linked"/><Step done label="Suspicious copy stored privately"/><Step done label="Incident record created"/><Step done={data.status!=="queued"} label="Media comparison"/><Step done={data.status==="completed"} label="Complaint analysis"/></div></Card>}
function Score({label,value}:{label:string;value:number|null|undefined}){return <div className="rounded-lg bg-muted p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-2 text-2xl font-semibold">{value===null||value===undefined?"Unavailable":`${value.toFixed(1)}%`}</div></div>}
function Signal({label,value}:{label:string;value:string}){return <div><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 font-medium">{value}</div></div>}
function Indicator({item}:{item:ComplaintIndicator}){return <div className="rounded-lg border p-3"><div className="flex justify-between gap-3 text-sm font-medium"><span>{item.rule}</span><span>+{item.points}</span></div><p className="mt-1 text-xs text-muted-foreground">{item.explanation}</p></div>}
function Step({label,done}:{label:string;done?:boolean}){return <div className="flex items-center gap-3 text-sm"><span className={done?"size-2 rounded-full bg-green-600":"size-2 rounded-full border border-muted-foreground"}/><span className={done?"":"text-muted-foreground"}>{label}</span></div>}
