"use client";
import Link from "next/link";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Plus,ArrowUpRight,Trash2} from "lucide-react";
import {AppShell} from "../../components/app-shell";
import {Badge,Button,Card} from "../../components/ui";
import {deleteIncident,getIncidents} from "../../lib/api";
import {EmptyState,ErrorState,LoadingState} from "../../components/async-state";
import {toast} from "sonner";

export default function Incidents(){const queryClient=useQueryClient();const query=useQuery({queryKey:["incidents"],queryFn:getIncidents});const remove=useMutation({mutationFn:deleteIncident,onSuccess:()=>{queryClient.invalidateQueries({queryKey:["incidents"]});toast.success("Incident deleted")},onError:error=>toast.error(error instanceof Error?error.message:"Could not delete incident")});const confirmDelete=(id:string)=>{if(window.confirm("Delete this incident and its evidence? This cannot be undone."))remove.mutate(id)};return <AppShell><div className="flex items-end justify-between gap-4"><div><p className="text-sm text-muted-foreground">Evidence cases</p><h1 className="mt-1 text-2xl font-semibold">Incidents</h1><p className="mt-2 text-sm text-muted-foreground">Track suspicious copies and complaint evidence without inventing conclusions.</p></div><Link href="/incidents/new"><Button><Plus size={16}/> Create Incident</Button></Link></div>{query.isLoading?<LoadingState label="Loading incidents…"/>:query.isError?<div className="mt-8"><ErrorState message="We couldn’t load incidents." onRetry={()=>query.refetch()}/></div>:!query.data?.length?<div className="mt-8"><EmptyState title="No incidents yet" description="Link a suspicious copy to a registered original when you are ready." action={<Link href="/incidents/new"><Button>Create Incident</Button></Link>}/></div>:<div className="mt-8 space-y-3">{query.data.map(incident=><Card key={incident.incident_id} className="flex items-center justify-between gap-4 p-5 hover:border-amber-500/50"><Link href={`/incidents/${incident.incident_id}`} className="min-w-0 flex-1"><div className="mono text-xs text-muted-foreground">{incident.incident_id}</div><div className="mt-2 truncate text-sm font-medium">{incident.suspicious_filename}</div><div className="mt-1 text-xs text-muted-foreground">@{incident.suspicious_username} · {new Date(incident.created_at).toLocaleDateString()}</div></Link><div className="flex items-center gap-3"><Badge tone="processing">{incident.status}</Badge><Link aria-label={`Open ${incident.incident_id}`} href={`/incidents/${incident.incident_id}`}><ArrowUpRight size={16} className="text-muted-foreground"/></Link><Button variant="ghost" size="icon" aria-label={`Delete ${incident.incident_id}`} onClick={()=>confirmDelete(incident.incident_id)} disabled={remove.isPending}><Trash2 size={15}/></Button></div></Card>)}</div>}</AppShell>}
