export type Proof={proof_id:string;title:string;instagram_username:string;claimed_publication_date:string;claimed_publication_url:string;original_filename:string;file_size:number;sha256:string;status:string;current_step:string;progress:number;evidence_completeness:number;created_at:string;duration:number|null;width:number|null;height:number|null;codec?:string|null;frame_rate?:number|null;audio_present?:boolean|null;audio_fingerprint?:string|null;transcript_status?:string;keyframes:{timestamp:number;hash:string;storage_key:string;storage_url?:string}[];transcript:string|null;media_url:string;events?:{timestamp:string;message:string}[]};
// Keep browser requests same-origin in production so the session cookie stays
// on the web host. Next rewrites /api requests to the private Zerops API host.
export const API=process.env.NEXT_PUBLIC_API_URL||"/api";
export type AuthUser={id:string;display_name:string;instagram_username:string;email:string};
const options:RequestInit={credentials:"include",cache:"no-store"};
export async function getMe():Promise<AuthUser>{const r=await fetch(`${API}/api/auth/me`,options);if(!r.ok)throw Error("Authentication required");return r.json()}
export async function demoLogin():Promise<AuthUser>{const r=await fetch(`${API}/api/auth/demo`,{method:"POST",credentials:"include"});if(!r.ok)throw Error("Could not start demo session");return r.json()}
export async function logout():Promise<void>{await fetch(`${API}/api/auth/logout`,{method:"POST",credentials:"include"})}
export async function getProofs(...args:any[]):Promise<Proof[]>{const params=args[0] as {search?:string;status?:string;page?:number;page_size?:number}|undefined;const query=new URLSearchParams();Object.entries(params||{}).forEach(([key,value])=>value&&query.set(key,String(value)));const r=await fetch(`${API}/api/proofs${query.toString()?`?${query}`:""}`,options);if(!r.ok)throw Error(r.status===401?"Authentication required":"Could not load proofs");return r.json()}
export async function getProof(id:string):Promise<Proof>{const r=await fetch(`${API}/api/proofs/${id}`,options);if(!r.ok)throw Error(r.status===401?"Authentication required":"Proof not found");return r.json()}
export async function retryProof(id:string):Promise<Proof>{const r=await fetch(`${API}/api/proofs/${id}/retry`,{method:"POST",credentials:"include"});if(!r.ok)throw Error((await r.json()).detail||"Could not retry proof");return r.json()}
export function mediaUrl(path:string){return path.startsWith("http")?path:`${API}${path}`}
export type ComplaintIndicator={rule:string;points:number;triggered:boolean;explanation:string};
export type Incident={incident_id:string;proof_id:number;suspicious_filename:string;suspicious_file_size:number;suspicious_username:string;claimed_publication_date:string;suspicious_url:string;caption:string;notes:string;status:string;stage:string;created_at:string;suspicious_media_url:string;visual_similarity:number|null;audio_similarity:number|null;transcript_similarity:number|null;timeline_confidence:number|null;combined_similarity:number|null;matching_segments:number|null;matching_audio_seconds:number|null;modifications:string[];complaint_extraction:{status:string;provider?:string;files?:{filename:string;status:string;text_available:boolean}[];fields?:Record<string,unknown>};suspicion_score:number|null;suspicion_band:string|null;suspicion_indicators:ComplaintIndicator[];community_matches:{report_id:number;identifier:string;matched_value:string;repeated_wording:string}[];community_summary:{label?:string;related_report_count?:number;payment_demand_occurrences?:number;creator_restrictions?:number;first_recorded_date?:string|null;simulated?:boolean};events?:{timestamp:string;message:string}[];evidence?:{filename:string;content_type:string;file_size:number;media_url:string}[]};
export async function getIncidents():Promise<Incident[]>{const r=await fetch(`${API}/api/incidents`,options);if(!r.ok)throw Error(r.status===401?"Authentication required":"Could not load incidents");return r.json()}
export async function getIncident(id:string):Promise<Incident>{const r=await fetch(`${API}/api/incidents/${id}`,options);if(!r.ok)throw Error(r.status===401?"Authentication required":"Incident not found");return r.json()}
export type ReportPreview={status:string;generated_at:string;incident_id:string;proof:Record<string,unknown>;suspicious:Record<string,unknown>;comparison:{visual:number|null;audio:number|null;transcript:number|null;timeline:number|null;combined:number|null;matching_segments:number|null;matching_audio_seconds:number|null;modifications:string[]};complaint:{status:string;provider:string;fields:Record<string,unknown>;files:{filename:string;status:string;text_available:boolean}[]};indicators:ComplaintIndicator[];community:{summary:Record<string,unknown>;matches:{report_id:number;identifier:string;matched_value:string}[]};evidence_files:{filename:string;type:string;size:number;sha256:string}[];missing:string[];disclaimer:string};
export async function getReportPreview(id:string):Promise<ReportPreview>{const r=await fetch(`${API}/api/incidents/${id}/report`,options);if(!r.ok)throw Error(r.status===401?"Authentication required":"Report unavailable");return r.json()}
export async function downloadReport(id:string):Promise<Blob>{const r=await fetch(`${API}/api/incidents/${id}/report.pdf`,{...options});if(!r.ok)throw Error("Could not generate report");return r.blob()}
