"use client";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {useForm} from "react-hook-form";
import {z} from "zod";
import {zodResolver} from "@hookform/resolvers/zod";
import {UploadCloud,ShieldCheck,ArrowLeft,ArrowRight,FileVideo,X,Check,LoaderCircle} from "lucide-react";
import Link from "next/link";
import {AppShell} from "../../components/app-shell";
import {Badge,Button,Card,Input,Textarea} from "../../components/ui";
import {API} from "../../lib/api";
import {toast} from "sonner";

const schema=z.object({title:z.string().min(2,"Add a title"),instagram_username:z.string().min(2,"Add your username"),claimed_publication_date:z.string().min(1,"Select a date"),claimed_publication_url:z.string().url("Enter a valid URL").or(z.literal("")),caption:z.string(),notes:z.string()});
type Form=z.infer<typeof schema>;
const steps=["Upload","Content details","Publication information","Review","Secure"];

export default function Register(){const [file,setFile]=useState<File|undefined>(undefined);const [step,setStep]=useState(0);const [submitting,setSubmitting]=useState(false);const [progress,setProgress]=useState(0);const [metadata,setMetadata]=useState<{duration:number;width:number;height:number}|undefined>(undefined);const [dragging,setDragging]=useState(false);const [error,setError]=useState("");const [previewUrl,setPreviewUrl]=useState("");const abortRef=useRef<AbortController|null>(null);const router=useRouter();const {register,handleSubmit,watch,trigger,formState:{errors}}=useForm<Form>({resolver:zodResolver(schema),defaultValues:{claimed_publication_date:new Date().toISOString().slice(0,10),caption:"",notes:""}});const values=watch();
 useEffect(()=>{if(!file){setPreviewUrl("");return}const url=URL.createObjectURL(file);setPreviewUrl(url);return()=>URL.revokeObjectURL(url)},[file]);
 function acceptFile(next?:File){if(!next)return;if(!["video/mp4","video/quicktime","video/webm"].includes(next.type)&&!next.name.toLowerCase().match(/\.(mp4|mov|webm)$/)){setError("Choose an MP4, MOV, or WebM file");return}if(next.size>100*1024*1024){setError("Maximum upload size is 100 MB");return}setError("");setFile(next)}
 async function nextStep(){setError("");if(step===0&&!file){setError("Choose an original video to continue");return}if(step===1&&!(await trigger(["title","instagram_username","caption","notes"])))return;if(step===2&&!(await trigger(["claimed_publication_date","claimed_publication_url"])))return;setStep(current=>Math.min(4,current+1))}
 function previousStep(){setError("");setStep(current=>Math.max(0,current-1))}
 function upload(body:FormData,signal:AbortSignal){return new Promise<any>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("POST",`${API}/api/proofs`);xhr.withCredentials=true;xhr.upload.onprogress=event=>{if(event.lengthComputable)setProgress(Math.round(event.loaded/event.total*100))};xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)resolve(JSON.parse(xhr.responseText));else reject(new Error(xhr.status===409?JSON.parse(xhr.responseText).detail||"This file is already registered":JSON.parse(xhr.responseText).detail||"Upload failed"))};xhr.onerror=()=>reject(new Error("Network error during upload"));xhr.onabort=()=>reject(new DOMException("Upload cancelled","AbortError"));signal.addEventListener("abort",()=>xhr.abort(),{once:true});xhr.send(body)})}
 async function submit(form:Form){if(step!==4||!file)return;setSubmitting(true);setProgress(0);setError("");const body=new FormData();body.append("file",file);Object.entries(form).forEach(([key,value])=>body.append(key,value||""));const controller=new AbortController();abortRef.current=controller;try{const proof=await upload(body,controller.signal);router.push(`/processing/${proof.proof_id}`)}catch(error){if(error instanceof DOMException&&error.name==="AbortError"){toast.message("Upload cancelled")}else{const message=error instanceof Error?error.message:"Upload failed";setError(message);toast.error(message)}setSubmitting(false)}}
 function cancelUpload(){abortRef.current?.abort();setSubmitting(false);setProgress(0)}
 return <AppShell><Link href="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={14}/> Back to dashboard</Link><div className="max-w-3xl"><p className="text-sm text-muted-foreground">Creator Proof registration</p><h1 className="mt-1 text-2xl font-semibold">Secure an original Reel</h1><p className="mt-2 text-sm text-muted-foreground">Create a private technical record with user-provided publication details.</p><div className="mt-8 grid grid-cols-5 gap-2">{steps.map((label,index)=><div key={label} className="min-w-0"><div className={index<=step?"h-1 rounded-full bg-blue-600":"h-1 rounded-full bg-muted"}/><div className={index===step?"mt-2 truncate text-xs font-medium":"mt-2 truncate text-xs text-muted-foreground"}>{index+1}. {label}</div></div>)}</div><form onSubmit={handleSubmit(submit)} className="mt-8 space-y-5">
 {step===0&&<Card className="p-6"><h2 className="font-semibold">Upload original video</h2><p className="mt-1 text-sm text-muted-foreground">MP4, MOV, or WebM · maximum 100 MB · recommended under 90 seconds</p>{!file?<label onDragEnter={event=>{event.preventDefault();setDragging(true)}} onDragOver={event=>event.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);acceptFile(event.dataTransfer.files[0])}} className={`mt-5 flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed px-6 py-16 text-center ${dragging?"border-blue-600 bg-blue-500/10":"bg-muted/30 hover:bg-muted"}`}><UploadCloud className="mb-3 text-muted-foreground" size={28}/><span className="text-sm font-medium">Drop your Reel here or choose a file</span><span className="mt-1 text-xs text-muted-foreground">Private storage · processed asynchronously</span><input type="file" accept="video/mp4,video/quicktime,video/webm" className="hidden" onChange={event=>acceptFile(event.target.files?.[0])}/></label>:<div className="mt-5 overflow-hidden rounded-xl border"><div className="aspect-video bg-black"><video src={previewUrl} controls className="h-full w-full" onLoadedMetadata={event=>setMetadata({duration:event.currentTarget.duration,width:event.currentTarget.videoWidth,height:event.currentTarget.videoHeight})}/></div><div className="flex items-center justify-between gap-4 p-4"><div className="flex min-w-0 items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-md bg-muted"><FileVideo size={16}/></span><div className="min-w-0"><p className="truncate text-sm font-medium">{file.name}</p><p className="mt-1 text-xs text-muted-foreground">{formatBytes(file.size)}{metadata&&` · ${formatDuration(metadata.duration)} · ${metadata.width}×${metadata.height}`}</p></div></div><button type="button" aria-label="Remove selected video" onClick={()=>{setFile(undefined);setMetadata(undefined)}} className="rounded-md p-2 text-muted-foreground hover:bg-muted"><X size={16}/></button></div></div>}{error&&<p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}</Card>}
 {step===1&&<Card className="space-y-5 p-6"><div><h2 className="font-semibold">Content details</h2><p className="mt-1 text-sm text-muted-foreground">Tell us how this original should be identified.</p></div><Field label="Reel title" error={errors.title?.message}><Input {...register("title")} placeholder="e.g. Morning light study"/></Field><Field label="Instagram username" error={errors.instagram_username?.message}><Input {...register("instagram_username")} placeholder="@thiru.creates"/></Field><Field label="Caption" hint="Optional"><Textarea {...register("caption")} rows={4} placeholder="Paste the original caption if useful"/></Field><Field label="Notes" hint="Optional"><Textarea {...register("notes")} rows={4} placeholder="Anything you want attached to the record"/></Field></Card>}
 {step===2&&<Card className="space-y-5 p-6"><div><h2 className="font-semibold">Publication information</h2><p className="mt-1 text-sm text-muted-foreground">These fields are user-provided and are not independently verified by CreatorShield.</p></div><Field label="Claimed publication date" hint="User-provided information" error={errors.claimed_publication_date?.message}><Input type="date" {...register("claimed_publication_date")}/></Field><Field label="Claimed Reel URL" hint="Optional · user-provided information" error={errors.claimed_publication_url?.message}><Input {...register("claimed_publication_url")} placeholder="https://instagram.com/reel/..."/></Field></Card>}
 {step===3&&<Card className="space-y-5 p-6"><div><h2 className="font-semibold">Review your Creator Proof</h2><p className="mt-1 text-sm text-muted-foreground">Confirm the record before it is secured.</p></div><ReviewRow label="Original video" value={file?`${file.name} · ${formatBytes(file.size)}`:"Not selected"}/><ReviewRow label="Reel title" value={values.title}/><ReviewRow label="Instagram username" value={values.instagram_username}/><ReviewRow label="Claimed publication date" value={values.claimed_publication_date}/><ReviewRow label="Claimed Reel URL" value={values.claimed_publication_url||"Not provided"}/><ReviewRow label="Caption" value={values.caption||"Not provided"}/><ReviewRow label="Notes" value={values.notes||"Not provided"}/></Card>}
 {step===4&&<Card className="p-8 text-center"><div className="mx-auto grid size-12 place-items-center rounded-full bg-green-500/10 text-green-600"><ShieldCheck size={24}/></div><h2 className="mt-4 text-lg font-semibold">Ready to secure your original</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Your file will be stored privately and processed asynchronously into a Creator Proof.</p>{submitting&&<div className="mx-auto mt-6 max-w-sm text-left"><div className="flex justify-between text-xs text-muted-foreground"><span>Uploading to private storage</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-blue-600 transition-all" style={{width:`${progress}%`}}/></div></div>}{error&&<p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}</Card>}
 <div className="flex items-center justify-between gap-4"><p className="max-w-md text-xs leading-5 text-muted-foreground">CreatorShield records technical evidence and user-provided publication information. It does not independently verify ownership.</p><div className="flex gap-2">{step>0&&!submitting&&<Button type="button" variant="outline" onClick={previousStep}>Back</Button>}{step<4&&<Button type="button" onClick={nextStep}>Continue <ArrowRight size={16}/></Button>}{step===4&&!submitting&&<Button type="submit"><ShieldCheck size={16}/> Secure Original Reel</Button>}{submitting&&<Button type="button" variant="outline" onClick={cancelUpload}><X size={15}/> Cancel upload</Button>}</div></div></form></div></AppShell>}
function Field({label,hint,error,children}:{label:string;hint?:string;error?:string;children:React.ReactNode}){return <label className="block text-sm font-medium">{label}{hint&&<span className="ml-2 text-xs font-normal text-muted-foreground">{hint}</span>}<div className="mt-2">{children}</div>{error&&<span className="mt-1 block text-xs text-red-600">{error}</span>}</label>}
function ReviewRow({label,value}:{label:string;value:string}){return <div className="flex flex-col gap-1 border-b pb-4 last:border-0 last:pb-0 sm:flex-row sm:justify-between"><span className="text-sm text-muted-foreground">{label}</span><span className="max-w-md break-words text-sm font-medium sm:text-right">{value}</span></div>}
function formatBytes(n:number){return n<1024*1024?`${Math.round(n/1024)} KB`:`${(n/1024/1024).toFixed(1)} MB`}
function formatDuration(n:number){return `${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,"0")}`}
