"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {usePathname,useRouter} from "next/navigation";
import {useTheme} from "next-themes";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {LayoutDashboard,ShieldCheck,AlertTriangle,FileText,Users,Settings,Sun,Moon,Menu,LogOut,Search,X,Bell} from "lucide-react";
import {AuthGuard} from "./auth-guard";
import {cn} from "./ui";
import {getProofs,logout} from "../lib/api";

export const nav=[ ["Dashboard","/dashboard",LayoutDashboard],["Proof Vault","/vault",ShieldCheck],["Incidents","/incidents",AlertTriangle],["Reports","/reports",FileText],["Community Intelligence","/community",Users] ] as const;
const labels:Record<string,string>={dashboard:"Dashboard",vault:"Proof Vault",incidents:"Incidents",reports:"Reports",community:"Community Intelligence",settings:"Settings"};

export function AppShell({children}:{children:React.ReactNode}){const path=usePathname();const {theme,setTheme}=useTheme();const router=useRouter();const queryClient=useQueryClient();const [mobileOpen,setMobileOpen]=useState(false);const [commandOpen,setCommandOpen]=useState(false);const proofQuery=useQuery({queryKey:["shell-proofs"],queryFn:getProofs,staleTime:2000});
 useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setCommandOpen(true)}if(event.key==="Escape"){setCommandOpen(false);setMobileOpen(false)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
 async function signOut(){await logout();queryClient.clear();router.replace("/login")}
 const currentLabel=labels[path?.split("/")[1]||"dashboard"]||"Workspace";const processingCount=proofQuery.data?.filter(proof=>proof.status==="processing").length||0;
 return <AuthGuard><div className="min-h-screen md:flex"><aside className="hidden w-60 shrink-0 border-r bg-card p-4 md:flex md:flex-col"><Brand/><Navigation path={path}/><SidebarFooter theme={theme} setTheme={setTheme} signOut={signOut}/></aside>{mobileOpen&&<div className="fixed inset-0 z-40 md:hidden"><button aria-label="Close navigation" className="absolute inset-0 bg-black/30" onClick={()=>setMobileOpen(false)}/><aside className="relative z-10 flex h-full w-72 flex-col border-r bg-card p-4"><div className="flex items-center justify-between"><Brand/><button aria-label="Close navigation" onClick={()=>setMobileOpen(false)} className="rounded-md p-2 hover:bg-muted"><X size={18}/></button></div><Navigation path={path} onNavigate={()=>setMobileOpen(false)}/><SidebarFooter theme={theme} setTheme={setTheme} signOut={signOut}/></aside></div>}<main className="min-w-0 flex-1"><header className="sticky top-0 z-10 flex h-14 items-center justify-between border-b bg-background/95 px-5 backdrop-blur"><div className="flex items-center gap-3"><button aria-label="Open navigation" onClick={()=>setMobileOpen(true)} className="rounded-md p-2 hover:bg-muted md:hidden"><Menu size={18}/></button><span className="text-sm text-muted-foreground">Workspace / <span className="text-foreground">{currentLabel}</span></span></div><div className="flex items-center gap-2"><button aria-label="Open command menu" onClick={()=>setCommandOpen(true)} className="hidden items-center gap-2 rounded-md border px-2.5 py-1.5 text-xs text-muted-foreground hover:bg-muted sm:flex"><Search size={13}/> Search <kbd className="mono rounded border px-1 text-[10px]">⌘K</kbd></button><button aria-label="Notifications" title="No new notifications" className="rounded-md p-2 text-muted-foreground hover:bg-muted"><Bell size={16}/></button><span className="hidden text-xs text-muted-foreground lg:block">Processing jobs <span className="ml-1 rounded-full bg-blue-500/10 px-2 py-1 text-blue-600">{processingCount}</span></span><div className="size-7 rounded-full bg-muted text-center text-xs leading-7">MC</div></div></header><div className="mx-auto max-w-[1440px] p-5 md:p-8">{children}</div></main></div>{commandOpen&&<CommandMenu close={()=>setCommandOpen(false)}/>}</AuthGuard>}

function Brand(){return <Link href="/dashboard" className="flex items-center gap-2 px-2 text-sm font-semibold"><span className="grid size-7 place-items-center rounded-md bg-primary text-primary-foreground"><ShieldCheck size={16}/></span>CreatorShield</Link>}
function Navigation({path,onNavigate}:{path:string|null;onNavigate?:()=>void}){return <nav className="mt-9 space-y-1">{nav.map(([label,href,Icon])=><Link onClick={onNavigate} key={href} href={href} className={cn("flex items-center gap-3 rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground",path===href&&"bg-muted font-medium text-foreground")}><Icon size={16}/>{label}</Link>)}</nav>}
function SidebarFooter({theme,setTheme,signOut}:{theme:string|undefined;setTheme:(theme:string)=>void;signOut:()=>void}){return <div className="mt-auto space-y-1"><Link href="/settings" className="flex items-center gap-3 rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-muted"><Settings size={16}/>Settings</Link><button onClick={()=>setTheme(theme==="dark"?"light":"dark")} className="flex w-full items-center gap-3 rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-muted">{theme==="dark"?<Sun size={16}/>:<Moon size={16}/>}Theme: {theme||"system"}</button><div className="mt-4 border-t px-3 pt-4"><div className="text-sm font-medium">Maya Chen</div><div className="mono text-xs text-muted-foreground">@maya.creates</div><button onClick={signOut} className="mt-3 flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><LogOut size={13}/> Sign out</button></div></div>}
function CommandMenu({close}:{close:()=>void}){const router=useRouter();const [query,setQuery]=useState("");const results=useMemo(()=>nav.filter(([label])=>label.toLowerCase().includes(query.toLowerCase())),[query]);function go(href:string){close();router.push(href)}return <div className="fixed inset-0 z-50 grid place-items-start bg-black/30 p-5 pt-[14vh]" onMouseDown={event=>{if(event.currentTarget===event.target)close()}}><div role="dialog" aria-modal="true" aria-label="Command menu" className="w-full max-w-lg overflow-hidden rounded-xl border bg-card shadow-xl"><div className="flex items-center gap-3 border-b px-4"><Search size={17} className="text-muted-foreground"/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search workspace" className="w-full bg-transparent py-4 text-sm outline-none"/><kbd className="mono text-[10px] text-muted-foreground">ESC</kbd></div><div className="p-2">{results.length?results.map(([label,href,Icon])=><button key={href} onClick={()=>go(href)} className="flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-sm hover:bg-muted"><Icon size={16} className="text-muted-foreground"/>{label}<span className="ml-auto text-xs text-muted-foreground">Open</span></button>):<p className="p-4 text-sm text-muted-foreground">No matching workspace destination.</p>}</div></div></div>}
